#cloud-config

hostname: ${hostname}
users:
 - name: ${localadmin}
   sudo: ["ALL=(ALL) NOPASSWD:ALL"]
   groups: [sudo]
   shell: /bin/bash
   ssh_authorized_keys:
    - ${sshauthorizedkey}
manage_resolv_conf: true
runcmd:
 - echo ${remotesshauthorizedkey} > /home/${localadmin}/.ssh/id_rsa
final_message: "The system is ready and prepped (took $UPTIME seconds)"